### ISSUE TITLE
请教大佬

### ISSUE THREAD

**Issue by Rsyncc** [iamazy/elasticsearch-sql#3]
我的es是7.2.1
[root@0409d5367365 bin]# ./elasticsearch-plugin install https://github.com/iamazy/elasticsearch-sql/releases/download/7.2.1.1/elasticsearch-sql-plugin-7.2.1.1.zip
-> Downloading https://github.com/iamazy/elasticsearch-sql/releases/download/7.2.1.1/elasticsearch-sql-plugin-7.2.1.1.zip
Exception in thread "main" java.io.FileNotFoundException: https://github.com/iamazy/elasticsearch-sql/releases/download/7.2.1.1/elasticsearch-sql-plugin-7.2.1.1.zip
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1909)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:246)
	at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:380)
	at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:278)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:229)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:216)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
提示找不到，请教下，要怎么改

**Comment by Rsyncc** [comment]
想离线安装，没找到下载地址，release里面没有7.2.1这个版本的

**Comment by iamazy** [comment]
> 想离线安装，没找到下载地址，release里面没有7.2.1这个版本的
好的，稍等，我编译一下

**Comment by Rsyncc** [comment]
在线等大佬，谢谢了

**Comment by iamazy** [comment]
> 在线等大佬，谢谢了

已经加了呀，见链接 https://github.com/iamazy/elasticsearch-sql/releases/download/v7.2.1.1/elasticsearch-sql-plugin-v7.2.1.1.zip

**Comment by Rsyncc** [comment]
[root@c4e7c8f397e3 bin]# ./elasticsearch-plugin install file:///tmp/elasticsearch-sql-plugin-v7.2.1.1.zip 
-> Downloading file:///tmp/elasticsearch-sql-plugin-v7.2.1.1.zip
[=================================================] 100%?? 
Exception in thread "main" java.nio.file.NoSuchFileException: /usr/share/elasticsearch/plugins/.installing-6105523430352407289/plugin-descriptor.properties
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:373)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:424)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:158)
	at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:156)
	at org.elasticsearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:723)
	at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:802)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:785)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:231)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:216)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)

**Comment by Rsyncc** [comment]
这个是不是我环境少什么包，大佬

**Comment by iamazy** [comment]
> 这个是不是我环境少什么包，大佬

说是没有这个文件`plugin-descriptor.properties`,不可能啊，不知道跟编译的系统有没有关系，昨晚是在自己的mac上编译的，jdk是11版本，之前都是jdk8编译的，我已经重新上传了，你再试试

**Comment by Rsyncc** [comment]
装好了，kibana重启了，开发工具那里感觉没啥变化

**Comment by iamazy** [comment]
> 装好了，kibana重启了，开发工具那里感觉没啥变化

这个和kibana没关系，应该重启es###

**Comment by Rsyncc** [comment]
多了一个graph，我研究研究，谢谢大佬
