### ISSUE TITLE
elasticsearch-7.9.2 是集群并带有密码 使用 elasticsearch-sql-jdbc-7.9.2 连接时有问题

### ISSUE THREAD

**Issue by suixindong** [iamazy/elasticsearch-sql#61]
es是集群，并带有密码
elasticsearch.yml中
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: certs/elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: certs/elastic-certificates.p12

elasticsearch版本为7.9.2
elasticsearch-sql插件版本为 elasticsearch-sql-7.9.2.0.zip
jdbc版本为： elasticsearch-sql-core-7.9.2.jar、elasticsearch-sql-jdbc-7.9.2.jar

使用样例中conn1()方式
多个地址：
private String ES_DB_URL = "jdbc:es://192.168.182.229:9350,192.168.182.230:9350,192.168.182.231:9350/alarm-20211117?useSSL=true&mode=cluster"
报如下错；
Caused by: java.net.UnknownHostException: 192.168.182.229:9350,192.168.182.230:9350,192.168.182.231: invalid IPv6 address
	at java.net.InetAddress.getAllByName(InetAddress.java:1169)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
15:23:01.889 [es_rest_client_sniffer[T#1]] DEBUG org.elasticsearch.client.RestClient - request [GET https://192.168.182.229:9350,192.168.182.230:9350,192.168.182.231:9350/_nodes/http?timeout=1000ms] failed
java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Connection pool shut down
	at org.apache.http.concurrent.BasicFuture.getResult(BasicFuture.java:71)
	at org.apache.http.concurrent.BasicFuture.get(BasicFuture.java:84)
	at org.apache.http.impl.nio.client.FutureWrapper.get(FutureWrapper.java:70)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:255)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:246)
	at org.elasticsearch.client.sniff.ElasticsearchNodesSniffer.sniff(ElasticsearchNodesSniffer.java:105)

单个地址：
private String ES_DB_URL = "jdbc:es://192.168.182.230:9350/alarm-20211117?useSSL=true&mode=cluster"
报错如下：
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.EngineInputRecord.bytesInCompletePacket(EngineInputRecord.java:156)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:868)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
15:25:13.899 [main] DEBUG org.elasticsearch.client.RestClient - request [POST https://192.168.182.230:9350/alarm-20211117/_search?typed_keys=true&max_concurrent_shard_requests=5&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&ignore_throttled=true&scroll=1m&search_type=query_then_fetch&batched_reduce_size=512&ccs_minimize_roundtrips=true] failed
java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at org.apache.http.concurrent.BasicFuture.getResult(BasicFuture.java:71)
	at org.apache.http.concurrent.BasicFuture.get(BasicFuture.java:84)
	at org.apache.http.impl.nio.client.FutureWrapper.get(FutureWrapper.java:70)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:255)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:246)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1613)

**Comment by suixindong** [comment]
> es是集群，并带有密码 elasticsearch.yml中 xpack.security.enabled: true xpack.security.transport.ssl.enabled: true xpack.security.transport.ssl.verification_mode: certificate xpack.security.transport.ssl.keystore.path: certs/elastic-certificates.p12 xpack.security.transport.ssl.truststore.path: certs/elastic-certificates.p12
> 
> elasticsearch版本为7.9.2 elasticsearch-sql插件版本为 elasticsearch-sql-7.9.2.0.zip jdbc版本为： elasticsearch-sql-core-7.9.2.jar、elasticsearch-sql-jdbc-7.9.2.jar
> 
> 使用样例中conn1()方式 多个地址： private String ES_DB_URL = "jdbc🇪🇸//192.168.182.229:9350,192.168.182.230:9350,192.168.182.231:9350/alarm-20211117?useSSL=true&mode=cluster" 报如下错； Caused by: java.net.UnknownHostException: 192.168.182.229:9350,192.168.182.230:9350,192.168.182.231: invalid IPv6 address at java.net.InetAddress.getAllByName(InetAddress.java:1169) at java.net.InetAddress.getAllByName(InetAddress.java:1126) at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) 15:23:01.889 [es_rest_client_sniffer[T#1]] DEBUG org.elasticsearch.client.RestClient - request [GET https://192.168.182.229:9350,192.168.182.230:9350,192.168.182.231:9350/_nodes/http?timeout=1000ms] failed java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Connection pool shut down at org.apache.http.concurrent.BasicFuture.getResult(BasicFuture.java:71) at org.apache.http.concurrent.BasicFuture.get(BasicFuture.java:84) at org.apache.http.impl.nio.client.FutureWrapper.get(FutureWrapper.java:70) at org.elasticsearch.client.RestClient.performRequest(RestClient.java:255) at org.elasticsearch.client.RestClient.performRequest(RestClient.java:246) at org.elasticsearch.client.sniff.ElasticsearchNodesSniffer.sniff(ElasticsearchNodesSniffer.java:105)
> 
> 单个地址： private String ES_DB_URL = "jdbc🇪🇸//192.168.182.230:9350/alarm-20211117?useSSL=true&mode=cluster" 报错如下： javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection? at sun.security.ssl.EngineInputRecord.bytesInCompletePacket(EngineInputRecord.java:156) at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:868) at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) 15:25:13.899 [main] DEBUG org.elasticsearch.client.RestClient - request [POST https://192.168.182.230:9350/alarm-20211117/_search?typed_keys=true&max_concurrent_shard_requests=5&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&ignore_throttled=true&scroll=1m&search_type=query_then_fetch&batched_reduce_size=512&ccs_minimize_roundtrips=true] failed java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection? at org.apache.http.concurrent.BasicFuture.getResult(BasicFuture.java:71) at org.apache.http.concurrent.BasicFuture.get(BasicFuture.java:84) at org.apache.http.impl.nio.client.FutureWrapper.get(FutureWrapper.java:70) at org.elasticsearch.client.RestClient.performRequest(RestClient.java:255) at org.elasticsearch.client.RestClient.performRequest(RestClient.java:246) at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1613)
